# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_Name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('individualBD', models.DateField(default='')),
                ('current_address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('probelemStatement', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('concept', models.CharField(max_length=20)),
                ('ownership', models.CharField(choices=[('IN', 'Individual'), ('CO', 'Company')], default='', max_length=200)),
                ('company_regDate', models.DateField(default='')),
                ('individual_NIN', models.CharField(max_length=14)),
                ('BusinessPlan', models.CharField(max_length=255)),
                ('FeasibilityStudy', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=3)),
                ('StudyUpload', models.FileField(upload_to='uploads/feasibility/%Y/%m/%d/')),
                ('ActionStatement', models.CharField(max_length=255)),
                ('EstimatedCost', models.IntegerField()),
                ('Innov_Stage', models.CharField(choices=[('CON', 'Concept'), ('DES', 'Design'), ('INN', 'Innovation'), ('PRO', 'Product'), ('ALP', 'Alpha/Beta testing'), ('PDN', 'Production testing'), ('TEA', 'Teaser Marketing'), ('FLD', 'Full Development')], default='', max_length=100)),
                ('Stage_Description', models.CharField(max_length=255)),
                ('Amount_invested', models.IntegerField()),
                ('Market_Study', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=14)),
                ('Market_Std_Descrip', models.CharField(max_length=255)),
                ('Market_STd_file', models.FileField(upload_to='uploads/mkt_study/%Y/%m/%d/')),
                ('Market', models.CharField(max_length=255)),
                ('Value_Added', models.CharField(max_length=255)),
                ('Time_to_product', models.CharField(max_length=255)),
                ('End_User_Invol', models.CharField(max_length=255)),
                ('Monitoring', models.CharField(max_length=255)),
                ('Fund_Raise', models.CharField(max_length=500)),
                ('Problems', models.CharField(max_length=300)),
                ('Impacts', models.CharField(max_length=300)),
                ('Remedies', models.CharField(max_length=255)),
                ('Safety', models.CharField(max_length=255)),
                ('Locations', models.CharField(max_length=255)),
                ('Sustainability', models.CharField(max_length=255)),
                ('MultiCultural', models.CharField(max_length=255)),
            ],
        ),
    ]
