# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_who_voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Member', to='Landing.member')),
            ],
        ),
    ]
