# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Vote_given',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='field_voted',
            field=models.CharField(choices=[('What problem Does the innovation seek to address?', 'Problem'), ('Why this Innovation? Do simillar Products exist?', 'Why'), ('Is it a new concept or an existing one? If new? Have you applied for any Intellectual property rights', 'New'), ('Is the innovation done by an individual or a company', 'Individual'), ('Summary of Business Plan', 'Business Plan'), ('Was any technical or economic feasilbity carried out?', 'Feasibility'), ('How do you plan to develop after Innovation?', 'Plan'), ('How do you plan to develop the product after innovation', 'Costs'), ('concept stage; design stage; invovation development ; product development; alpha / beta testing; production testing; teaser marketing;or full development', 'Innovation Stage'), ('Finances already invested in the product', 'Finances'), ('Was any market study/ customer feedback or market research done? If so details?', 'MarketStudy'), ('How exactly does the innovation improves the lives of citizens?', 'Improve'), ('What is the Target Market?', 'Target Market'), ('Estimated time for design to production ? (If at design stage else time from that stage to production)', 'Design to Production'), ('Who is part of the design prototyping, implementing, monitoring and evaluating?', 'Involved'), ('How will the progress be monitored to obtain quick feedback to further spur development?', 'Progress'), ('Have you identified potential locations or use ICT ministrys site for devlopment?', 'Potential Locations'), ('How will you intend to raise finance and how the same be utilised?', 'Raise Finance'), ('How do you plan to scale upwards  and outwards and how will this scaling be sustainable?', 'Scalability'), ('is your product able to meet demands/needs outside the boundaries of uganda and if so, where?', 'Beyond Uganda'), ('Detail potential problems youll face, the Impacts and remedies to said problems?', 'Problems'), ('Identify any safety issues for the end users  while using the innovation product?', 'Safety')], default='which', max_length=255),
        ),
        migrations.AddField(
            model_name='vote',
            name='innovation_voted',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Innovation', to='Landing.Submision'),
            preserve_default=False,
        ),
    ]
