# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0004_formtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submision',
            name='Innov_Stage',
        ),
        migrations.AddField(
            model_name='submision',
            name='Commncementdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of team inception'),
        ),
        migrations.AddField(
            model_name='submision',
            name='InnovationStage',
            field=models.CharField(choices=[('CON', 'Concept'), ('DES', 'Design'), ('INN', 'Innovation'), ('PRO', 'Product'), ('ALP', 'Alpha/Beta testing'), ('PDN', 'Production testing'), ('TEA', 'Teaser Marketing'), ('FLD', 'Full Development')], default='', max_length=100, verbose_name='What is the current phase of innoation'),
        ),
        migrations.AddField(
            model_name='submision',
            name='duration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Duration within the hub'),
        ),
        migrations.AddField(
            model_name='submision',
            name='hubName',
            field=models.CharField(default='', max_length=40, verbose_name='Name of the hub you reside in?'),
        ),
        migrations.AddField(
            model_name='submision',
            name='teamName',
            field=models.CharField(default='', max_length=40, verbose_name='Name of your team'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='ActionStatement',
            field=models.TextField(max_length=255, verbose_name='How do you plan to develop the product after innovation?'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Amount_invested',
            field=models.IntegerField(verbose_name='Amount Invested to date'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='BusinessPlan',
            field=models.TextField(max_length=255, verbose_name='Summary of business plan'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='End_User_Invol',
            field=models.TextField(max_length=255, verbose_name='End User Involvement'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='FeasibilityStudy',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=3, verbose_name='Was any technical/economic feasibility study carried out'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Fund_Raise',
            field=models.TextField(max_length=500, verbose_name='How do you intend to raise funds and utilise them?'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Impacts',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Locations',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Market',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Market_STd_file',
            field=models.FileField(blank=True, upload_to='uploads/mkt_study/%Y/%m/%d/', verbose_name='Please upload the findings of your study'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Market_Std_Descrip',
            field=models.TextField(blank=True, max_length=255, verbose_name='If yes, provide details.'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Market_Study',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='', max_length=14, verbose_name='Did you carry out any market study/Customer feedback or market research?'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Monitoring',
            field=models.TextField(max_length=255, verbose_name='How will the progress be monitored to obtain quick feedback to spur development?'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='MultiCultural',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Problems',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Remedies',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Safety',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Stage_Description',
            field=models.TextField(max_length=255, verbose_name='Describe the current stage of innovation'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='StudyUpload',
            field=models.FileField(blank=True, upload_to='uploads/feasibility/%Y/%m/%d/', verbose_name='If yes, please attach the findings of this study'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Sustainability',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Time_to_product',
            field=models.TextField(max_length=255, verbose_name='What is the estimated time from design to production'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='Value_Added',
            field=models.TextField(max_length=255, verbose_name="How does it improve citizen's lives"),
        ),
        migrations.AlterField(
            model_name='submision',
            name='background',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='submision',
            name='company_regDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Company registration date'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='concept',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='submision',
            name='individualBD',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Individual Date of birth'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='individual_NIN',
            field=models.CharField(max_length=14, verbose_name='NIN Number'),
        ),
        migrations.AlterField(
            model_name='submision',
            name='ownership',
            field=models.CharField(choices=[('IN', 'Individual'), ('TO', 'Team'), ('HU', 'Hub'), ('CO', 'Company')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='submision',
            name='probelemStatement',
            field=models.TextField(max_length=200, verbose_name='Problem Statement'),
        ),
    ]
