# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0005_auto_20171013_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submision',
            name='individualBD',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Individual Date of birth'),
        ),
    ]
